[general]
email = "pavansundar1999@gmail.com"

[secrets]


OPENAI_API_KEY = "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"
AMADEUS_API_KEY = "rqA3aNRf3YpGLGaJp0FYlgKoNLoBTQmr"
AMADEUS_API_SECRET = "XNmPIcrdCfqwgq1U"
google_maps_api_key = "AIzaSyD0dsuiKXT9nz7JeF9JoXOyRWREnviFhPo"
weather_api_key = "8af06b6749f28caa081c51424fac6e6c"
serpapi_key = "c71f955b7e9a34c69113a5cd30aede628d330ba267a73c1bb09ff52229bd2726"
huggingface_token = "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"
